import { Frank_Ruhl_Libre } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/navBar";
import ThemeProvider from "./theme";
import Script from "next/script";

const frankRuhlLibre = Frank_Ruhl_Libre({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "College Counsel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <head>
     <script id="messenger-widget-b" src="https://cdn.botpenguin.com/website-bot.js" defer>6647981f07af820cc774bacd,664797f8881a65150d0aa425</script>
      </head>
      <body className={frankRuhlLibre.className}>
       <nav>
        <NavBar/>
       </nav>
        <ThemeProvider>
          { children }
          </ThemeProvider>
          </body>
    </html>
  );
}
