import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/navBar";
import ThemeProvider from "./theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "College Counsel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <nav>
        <NavBar/>
       </nav>
        <ThemeProvider>
          { children }
          </ThemeProvider>
          </body>
    </html>
  );
}
